source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Keyboard_Example', :exclusive => true do
  pod "Keyboard", :path => "../"
end

target 'Keyboard_Tests', :exclusive => true do
  pod "Keyboard", :path => "../"

  
end
